chore(node): drop 16 support as EOL
americanexpress/holocron pull request #167
Opened 2024-01-19 18:18 UTC by JAdshead

## Description

Drop support for Node 16 as its EOL

## Motivation and Context

Do not support dead versions of Node

## How Has This Been Tested?

N/A

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] My changes are in sync with the code style of this project.
- [ ] There aren't any other open Pull Requests for the same issue/update.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] This change impacts caching for client browsers.
- [ ] This change adds additional environment variable requirements for Holocron users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using Holocron?

2024-01-23 18:50 UTC, dogpatch626 approved these changes

2024-01-25 03:20 UTC, giulianok approved these changes

2024-01-25 05:31 UTC, 10xLaCroixDrinker requested changes

2024-01-25 05:31 UTC, 10xLaCroixDrinker commented on .github/workflows/health-check.yml
> +        node: ['18.x']
```suggestion
        node: ['18.x', '20.x']
```

2024-01-25 05:31 UTC, 10xLaCroixDrinker commented on .github/workflows/tests.yml
> +        node: ['18.x']
```suggestion
        node: ['18.x', '20.x']
```

2024-01-25 20:08 UTC, 10xLaCroixDrinker approved these changes

2024-01-25 20:25 UTC, dogpatch626 approved these changes

2024-01-25 21:10 UTC, merged